[default]
Mode = WINBOND_W25N01GV
DeviceName = W25N01GV
Manufacturer = Winbond
BlockSize = 64
PageSize = 2048
SectorSize = 512
SpareAreaSize = 64
SectorsPerPage = 4
MetadataSize = 0
UseECC = True
ECC_Offset = 8
ECC_Errors = 1
ECC_Bytes_Per_Sector = 6
ECC_Polynom = 0x0
File_Offset = 0x0
